export interface LeaseAnswers {
  LeaseCreationDate: string;
  LeaseStartDate: string;
  LeaseEndDate: string;
  BuildingName: string;
  Address: string;
  'Apt#': string;
  AptFlr: string;
  UtilitiesIncluded: string;
  OwnerName: string;
  OwnerAddress: string;
  OwnerEmail: string;
  TenantName: string;
  TenantEmail: string;
  TenantCurrentAddress: string;
  Occupants: string;
  RentAmount: string;
  PaymentMethods: string;
  SecurityDeposit: string;
  SDBank: string;
  SDBankAddress: string;
  Furniture: string;
  OwnershipWork: string;
  ApprovedAlterations: string;
  SubMeteredUtilities: string;
  TTApplianceRepairCost: string;
  MinInsuranceNum: string;
  MinInsuranceTxt: string;
  MaxInsuranceNum: string;
  MaxInsuranceTxt: string;
  PetTypes: string;
  OwnersBroker: string;
  TenantsBroker: string;
  ExtensionYears: string;
  ExtensionStartDate: string;
  ExtensionEndDate: string;
  ExtensionRent: string;
  // Rider answers
  selectedRiders: string;
  wg_DeadlineDate: string;
  wg_SignDate: string;
  wg_NoticeDate: string;
  TenantFirstName: string;
  TenantLastName: string;
  TenantMiddleInitial: string;
  City: string;
  State: string;
  Zip: string;
  TenantPhone: string;
  bb_buildingEradicatedFloors: string;
  bb_buildingNotEradicatedFloors: string;
  bb_otherText: string;
  bb_TenantSignDate: string;
  bb_OwnerSignDate: string;
  aller_SignDate: string;
  TenantCount: string;
  tenantList: string;
  tenantEmails: string;
  GuarantorCount: string;
  guarantors: string;
  // New rider answer keys
  spr_lastInspectDate: string;
  knob_returnByDate: string;
  smk_otherText: string;
}

export interface LeaseFlags {
  furnitureIncluded: boolean;
  hasOutdoorSpace: boolean;
  builtBefore1978: boolean;
  hasAlarm: boolean;
  approvedAlterations: boolean;
  subMetered: boolean;
  applianceRepair: boolean;
  glInsurance: boolean;
  extension: boolean;
  petsAllowed: boolean;
  bicyclesForbidden: boolean;
  brokersRetained: boolean;
  ownerWork: boolean;
  memorandum: boolean;
  guarantyIncluded: boolean;
  // Rider flags
  wg_childPresent: boolean;
  wg_noChild: boolean;
  wg_guardsInstalledAll: boolean;
  wg_guardsNotInstalled: boolean;
  wg_guardsNeedRepair: boolean;
  wg_guardsNoRepair: boolean;
  wg_wantGuardsAnyway: boolean;
  wg_child5Present: boolean;
  wg_haveGuardsNeedRepair: boolean;
  bb_noHistory: boolean;
  bb_buildingEradicated: boolean;
  bb_buildingNotEradicated: boolean;
  bb_aptEradicated: boolean;
  bb_aptNotEradicated: boolean;
  bb_other: boolean;
  // Sprinkler rider flags
  spr_hasSystem: boolean;
  spr_noSystem: boolean;
  // Stove knob rider flags
  knob_wantCovers: boolean;
  knob_wantPermKnobs: boolean;
  knob_childYes: boolean;
  knob_childNo: boolean;
  // Smoking rider flags
  smk_insideUnits: boolean;
  smk_outsideUnits: boolean;
  smk_outdoorCommon: boolean;
  smk_within15ft: boolean;
  smk_other: boolean;
  // Flood rider flags
  fld_femaFloodplain: boolean;
  fld_sfha: boolean;
  fld_moderate: boolean;
  fld_floodDamage: boolean;
  // Federal lead rider flags
  fl_knownPresent: boolean;
  fl_noKnowledge: boolean;
  fl_recordsProvided: boolean;
  fl_noRecords: boolean;
}

export const DEFAULT_ANSWERS: LeaseAnswers = {
  LeaseCreationDate: new Date().toLocaleDateString('en-CA'),
  LeaseStartDate: '',
  LeaseEndDate: '',
  BuildingName: '',
  Address: '',
  'Apt#': '',
  AptFlr: '',
  UtilitiesIncluded: '',
  OwnerName: '',
  OwnerAddress: '',
  OwnerEmail: 'leasing@auranewyork.com',
  TenantName: '',
  TenantEmail: '',
  TenantCurrentAddress: '',
  Occupants: '',
  RentAmount: '',
  PaymentMethods: '',
  SecurityDeposit: '',
  SDBank: '',
  SDBankAddress: '',
  Furniture: '',
  OwnershipWork: '',
  ApprovedAlterations: '',
  SubMeteredUtilities: '',
  TTApplianceRepairCost: '',
  MinInsuranceNum: '',
  MinInsuranceTxt: '',
  MaxInsuranceNum: '',
  MaxInsuranceTxt: '',
  PetTypes: '',
  OwnersBroker: '',
  TenantsBroker: '',
  ExtensionYears: '',
  ExtensionStartDate: '',
  ExtensionEndDate: '',
  ExtensionRent: '',
  selectedRiders: '',
  wg_DeadlineDate: '',
  wg_SignDate: '',
  wg_NoticeDate: '',
  TenantFirstName: '',
  TenantLastName: '',
  TenantMiddleInitial: '',
  City: '',
  State: '',
  Zip: '',
  TenantPhone: '',
  bb_buildingEradicatedFloors: '',
  bb_buildingNotEradicatedFloors: '',
  bb_otherText: '',
  bb_TenantSignDate: '',
  bb_OwnerSignDate: '',
  aller_SignDate: '',
  TenantCount: '',
  tenantList: '[]',
  tenantEmails: '[]',
  GuarantorCount: '0',
  guarantors: '[]',
  spr_lastInspectDate: '',
  knob_returnByDate: '',
  smk_otherText: '',
};

export const DEFAULT_FLAGS: LeaseFlags = {
  furnitureIncluded: false,
  hasOutdoorSpace: false,
  builtBefore1978: false,
  hasAlarm: false,
  approvedAlterations: false,
  subMetered: false,
  applianceRepair: false,
  glInsurance: false,
  extension: false,
  petsAllowed: false,
  bicyclesForbidden: false,
  brokersRetained: false,
  ownerWork: false,
  memorandum: false,
  guarantyIncluded: true,
  wg_childPresent: false,
  wg_noChild: false,
  wg_guardsInstalledAll: false,
  wg_guardsNotInstalled: false,
  wg_guardsNeedRepair: false,
  wg_guardsNoRepair: false,
  wg_wantGuardsAnyway: false,
  wg_child5Present: false,
  wg_haveGuardsNeedRepair: false,
  bb_noHistory: false,
  bb_buildingEradicated: false,
  bb_buildingNotEradicated: false,
  bb_aptEradicated: false,
  bb_aptNotEradicated: false,
  bb_other: false,
  spr_hasSystem: false,
  spr_noSystem: false,
  knob_wantCovers: false,
  knob_wantPermKnobs: false,
  knob_childYes: false,
  knob_childNo: false,
  smk_insideUnits: false,
  smk_outsideUnits: false,
  smk_outdoorCommon: false,
  smk_within15ft: false,
  smk_other: false,
  fld_femaFloodplain: false,
  fld_sfha: false,
  fld_moderate: false,
  fld_floodDamage: false,
  fl_knownPresent: false,
  fl_noKnowledge: false,
  fl_recordsProvided: false,
  fl_noRecords: false,
};
