import type { LeaseAnswers, LeaseFlags } from '@/types';

export const TEST_ANSWERS: LeaseAnswers = {
  LeaseCreationDate: '2026-06-16',
  LeaseStartDate: '2026-07-01',
  LeaseEndDate: '2027-06-30',
  BuildingName: 'The Sky',
  Address: '605 W 42nd St, New York, NY 10036',
  'Apt#': '58J',
  AptFlr: '58',
  UtilitiesIncluded: 'Heat, Hot Water',
  OwnerName: 'Sky Owner LLC',
  OwnerAddress: '605 W 42nd St, New York, NY 10036',
  OwnerEmail: 'leasing@auranewyork.com',
  TenantName: 'Jane Doe, John Roe',
  TenantEmail: 'jane.doe@example.com',
  TenantCurrentAddress: '1 Main St, Apt 2, Brooklyn, NY 11201',
  Occupants: 'Jane Doe, John Roe',
  RentAmount: '6600',
  PaymentMethods: 'Zelle',
  SecurityDeposit: '6600',
  SDBank: 'Citibank, N.A.',
  SDBankAddress: '388 Greenwich St, New York, NY 10013',
  Furniture: 'Sofa, bed frame, dining table',
  OwnershipWork: 'Repaint living room; replace kitchen faucet',
  ApprovedAlterations: 'Install floating wall shelves in the second bedroom',
  SubMeteredUtilities: 'Electricity',
  TTApplianceRepairCost: '100',
  MinInsuranceNum: '100000',
  MinInsuranceTxt: 'One Hundred Thousand',
  MaxInsuranceNum: '300000',
  MaxInsuranceTxt: 'Three Hundred Thousand',
  PetTypes: 'One (1) dog under 40 lbs',
  OwnersBroker: 'Aura New York',
  TenantsBroker: 'ABC Realty',
  ExtensionYears: '1',
  ExtensionStartDate: '2027-07-01',
  ExtensionEndDate: '2028-06-30',
  ExtensionRent: '6900',
};

export const TEST_FLAGS: LeaseFlags = {
  furnitureIncluded: true,
  hasOutdoorSpace: true,
  builtBefore1978: true,
  hasAlarm: true,
  approvedAlterations: true,
  subMetered: true,
  applianceRepair: true,
  glInsurance: true,
  extension: true,
  petsAllowed: true,
  bicyclesForbidden: true,
  brokersRetained: true,
  ownerWork: true,
  memorandum: true,
};
