import type { LeaseAnswers, LeaseFlags } from '@/types';

export const TEST_ANSWERS: LeaseAnswers = {
  LeaseCreationDate: new Date().toLocaleDateString('en-CA'),
  LeaseStartDate: '2026-07-01',
  LeaseEndDate: '2027-06-30',
  BuildingName: 'The Sky',
  Address: '605 W 42nd St, New York, NY 10036',
  'Apt#': '58J',
  AptFlr: '58',
  UtilitiesIncluded: 'Heat, Hot Water',
  OwnerName: 'Sky Owner LLC',
  OwnerAddress: '605 W 42nd St, New York, NY 10036',
  OwnerEmail: 'leasing@auranewyork.com',
  TenantName: 'Jane Doe, John Roe',
  TenantEmail: 'jane.doe@example.com',
  TenantCurrentAddress: '1 Main St, Apt 2, Brooklyn, NY 11201',
  Occupants: 'Jane Doe, John Roe',
  RentAmount: '6600',
  PaymentMethods: 'Zelle',
  SecurityDeposit: '6600',
  SDBank: 'Citibank, N.A.',
  SDBankAddress: '388 Greenwich St, New York, NY 10013',
  Furniture: 'Sofa, bed frame, dining table',
  OwnershipWork: 'Repaint living room; replace kitchen faucet',
  ApprovedAlterations: 'Install floating wall shelves in the second bedroom',
  SubMeteredUtilities: 'Electricity',
  TTApplianceRepairCost: '100',
  MinInsuranceNum: '100000',
  MinInsuranceTxt: 'One Hundred Thousand',
  MaxInsuranceNum: '300000',
  MaxInsuranceTxt: 'Three Hundred Thousand',
  PetTypes: 'One (1) dog under 40 lbs',
  OwnersBroker: 'Aura New York',
  TenantsBroker: 'ABC Realty',
  ExtensionYears: '1',
  ExtensionStartDate: '2027-07-01',
  ExtensionEndDate: '2028-06-30',
  ExtensionRent: '6900',
  // Rider answers
  selectedRiders: 'windowGuard,leadWindowAnnual,bedbug,allergen,windowGuardES',
  wg_DeadlineDate: '2026-07-15',
  wg_SignDate: '',
  wg_NoticeDate: '2026-06-16',
  TenantFirstName: 'Jane',
  TenantLastName: 'Doe',
  TenantMiddleInitial: 'M',
  City: 'New York',
  State: 'NY',
  Zip: '10036',
  TenantPhone: '212-555-0199',
  bb_buildingEradicatedFloors: '',
  bb_buildingNotEradicatedFloors: '',
  bb_otherText: '',
  bb_TenantSignDate: '',
  bb_OwnerSignDate: '',
  aller_SignDate: '',
  TenantCount: '2',
  tenantList: '[{"first":"Jane","middle":"M","last":"Doe","phone":"212-555-0199","email":"jane.doe@example.com"},{"first":"John","middle":"","last":"Roe","phone":"212-555-0200","email":"john.roe@example.com"}]',
  tenantEmails: '["jane.doe@example.com","john.roe@example.com"]',
  GuarantorCount: '1',
  guarantors: '[{"GuarantorName":"Mary Guarantor","GuarantorAddress":"10 Guarantor Ln, New York, NY 10001","name":"Mary Guarantor","email":""}]',
  spr_lastInspectDate: '',
  knob_returnByDate: '',
  smk_otherText: '',
};

export const TEST_FLAGS: LeaseFlags = {
  furnitureIncluded: true,
  hasOutdoorSpace: true,
  builtBefore1978: true,
  hasAlarm: true,
  approvedAlterations: true,
  subMetered: true,
  applianceRepair: true,
  glInsurance: true,
  extension: true,
  petsAllowed: true,
  bicyclesForbidden: true,
  brokersRetained: true,
  ownerWork: true,
  memorandum: true,
  guarantyIncluded: true,
  // Rider flags
  wg_childPresent: true,
  wg_noChild: false,
  wg_guardsInstalledAll: true,
  wg_guardsNotInstalled: false,
  wg_guardsNeedRepair: false,
  wg_guardsNoRepair: true,
  wg_wantGuardsAnyway: false,
  wg_child5Present: false,
  wg_haveGuardsNeedRepair: false,
  bb_noHistory: true,
  bb_buildingEradicated: false,
  bb_buildingNotEradicated: false,
  bb_aptEradicated: false,
  bb_aptNotEradicated: false,
  bb_other: false,
  spr_hasSystem: true,
  spr_noSystem: false,
  knob_wantCovers: true,
  knob_wantPermKnobs: false,
  knob_childYes: false,
  knob_childNo: true,
  smk_insideUnits: true,
  smk_outsideUnits: true,
  smk_outdoorCommon: false,
  smk_within15ft: false,
  smk_other: false,
  fld_femaFloodplain: false,
  fld_sfha: false,
  fld_moderate: false,
  fld_floodDamage: false,
  fl_knownPresent: false,
  fl_noKnowledge: false,
  fl_recordsProvided: false,
  fl_noRecords: false,
};
